In [5]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("/content/mega_data_cleaning_dataset - Sheet1.csv")
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8287,Deborah Garcia,11,Mle,Cape Verde,Maine,Lake Albert,timothy71@hotmail.com,2025-02-18,Inactive,...,17,2025-01-30,2025-03-19,Cash,1.2,NaN,NaN,2025-02-16,web,2742.27
9996,8932,Donald Pineda,69,Female,NaN,Pennsylvania,Raymondbury,gsmith@hotmail.com,2022-07-03,NaN,...,-5,2025-05-22,2025-04-12,Credit,3.7,Cut talk father trade last Democrat participant.,VIP,2025-09-18,Web,-792.65
9997,6328,Alexandria Moore,-5,Other,Cocos (Keeling) Islands,Pennsylvania,Port Frank,morgansamantha@hotmail.com,2023-03-01,Banned,...,4,2025-02-18,2025-08-14,UPI,4.6,Place our focus television story tonight.,Returning,NaN,App,-138.16
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaN,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [8]:
#1.Identify and remove duplicate rows in the dataset.
df = df.drop_duplicates()
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8287,Deborah Garcia,11,Mle,Cape Verde,Maine,Lake Albert,timothy71@hotmail.com,2025-02-18,Inactive,...,17,2025-01-30,2025-03-19,Cash,1.2,NaN,NaN,2025-02-16,web,2742.27
9996,8932,Donald Pineda,69,Female,NaN,Pennsylvania,Raymondbury,gsmith@hotmail.com,2022-07-03,NaN,...,-5,2025-05-22,2025-04-12,Credit,3.7,Cut talk father trade last Democrat participant.,VIP,2025-09-18,Web,-792.65
9997,6328,Alexandria Moore,-5,Other,Cocos (Keeling) Islands,Pennsylvania,Port Frank,morgansamantha@hotmail.com,2023-03-01,Banned,...,4,2025-02-18,2025-08-14,UPI,4.6,Place our focus television story tonight.,Returning,NaN,App,-138.16
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaN,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [9]:
#	2.Identify and remove duplicate Customer_IDs.
df = df.drop_duplicates(subset='Customer_ID')
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2919,Tyler Hunter,44,Female,Guam,Indiana,Tylerville,ashley87@yahoo.com,2021-10-23,NaN,...,6,2025-07-19,2025-07-13,Debit,2.1,NaN,New,2025-09-22,Web,3598.86
9993,8538,Harry Carter,108,Female,Tokelau,Texas,West Annaberg,uhayes@clark-webb.com,2023-09-30,Active,...,19,2025-04-15,2025-05-19,Credit,1.6,Six if soldier south support find spring.,New,2025-08-01,Web,1164.13
9994,1905,Deborah Young,128,f,Tuvalu,Tennessee,East Anthonytown,james28@yahoo.com,2020-05-04,NaN,...,19,2025-10-01,2025-04-11,UPI,2.8,Shake fill thank buy.,NaN,2025-06-11,app,6487.55
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaN,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [10]:
#3.	Identify and remove duplicate Emails.
df=df.drop_duplicates(subset=['Email'])
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2919,Tyler Hunter,44,Female,Guam,Indiana,Tylerville,ashley87@yahoo.com,2021-10-23,NaN,...,6,2025-07-19,2025-07-13,Debit,2.1,NaN,New,2025-09-22,Web,3598.86
9993,8538,Harry Carter,108,Female,Tokelau,Texas,West Annaberg,uhayes@clark-webb.com,2023-09-30,Active,...,19,2025-04-15,2025-05-19,Credit,1.6,Six if soldier south support find spring.,New,2025-08-01,Web,1164.13
9994,1905,Deborah Young,128,f,Tuvalu,Tennessee,East Anthonytown,james28@yahoo.com,2020-05-04,NaN,...,19,2025-10-01,2025-04-11,UPI,2.8,Shake fill thank buy.,NaN,2025-06-11,app,6487.55
9998,8121,NaN,110,Male,Equatorial Guinea,Maine,Jacquelinefort,courtneybradley@day-gilbert.com,2022-11-20,Inactive,...,8,2025-05-30,2025-03-21,Credit,0.3,Region degree rest never it.,VIP,NaN,Phone,1542.56
9999,2851,Kathleen Leblanc,67,Mle,Albania,Virginia,South Michelle,kristincook@thompson-campbell.info,2024-04-01,Inactive,...,15,2025-04-07,2025-07-01,Cash,0.9,Surface bill everyone music paper us beyond.,NaN,2025-05-24,Phone,5585.55

In [11]:

#	4.Identify and remove duplicate Product_IDs.
df=df.drop_duplicates(subset=['Product_ID'])
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [12]:
#5.	Fill missing Name values with "Unknown".
df['Name'].fillna('Unknown')

0          Larry Wallace
1           Shawn Palmer
2          Daniel Cortez
3           Cindy Barber
4          William Patel
              ...
2955             Unknown
3032       Paula Wheeler
3034        Karen Miller
3039    Kirk Clayton PhD
3298          Angel Hood
Name: Name, Length: 500, dtype: object

In [13]:
#6.	Fill missing Email values with "noemail@example.com".
df['Email'].fillna('noemail@example.com')

0       gonzalezbrandi@shaffer-lambert.com
1                 davidmendoza@hotmail.com
2                    hoffmancole@yahoo.com
3                 carpenterlinda@yahoo.com
4          blairivan@lyons-christensen.org
                       ...
2955                  nicholas42@yahoo.com
3032                       hmunoz@kent.com
3034                      zsmall@gmail.com
3039                   cbennett@wright.com
3298                      omar32@yahoo.com
Name: Email, Length: 500, dtype: object

In [14]:
#7.	Fill missing Product_Name values with "Misc".
df['Product_Name'].fillna('Misc')

0         police
1       training
2        compare
3           miss
4           deal
          ...
2955      almost
3032       truth
3034      leader
3039        real
3298        card
Name: Product_Name, Length: 500, dtype: object

In [15]:
#8.	Fill missing Category values with "Misc".
df['Category'].fillna('Misc')

0              Misc
1          Clothing
2              Misc
3              Misc
4       Electronics
           ...
2955    Electronics
3032           Misc
3034    Electronics
3039           Misc
3298       Clothing
Name: Category, Length: 500, dtype: object

In [16]:

#9.	Fill missing Feedback_Score values with the median feedback per product.
x= df.groupby('Product_ID')['Feedback_Score'].transform('median')
df['Feedback_Score'] = df['Feedback_Score'].fillna(x)
df

/tmp/ipython-input-3846776950.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Feedback_Score'] = df['Feedback_Score'].fillna(x)

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [17]:
#10.	Fill missing Quantity values with 1.
df['Quantity'].fillna(1)

0       12
1        9
2        0
3        9
4        7
        ..
2955     3
3032    15
3034    15
3039     5
3298    15
Name: Quantity, Length: 500, dtype: int64

In [18]:
#11.	Remove rows where Price is negative
df = df[df['Price'] >= 0]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [19]:
#12.	Remove rows where Price is zero.
df = df[df['Price'] != 0]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [20]:
#13.	Remove rows where Quantity is negative.
df = df[df['Quantity'] >= 0]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [21]:
#14.	Remove rows where Age is less than 0 or greater than 120
df = df[(df['Age'] >= 0) & (df['Age'] <= 120)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3034,3786,Karen Miller,22,f,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaN,web,6547.95
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95
3298,5796,Angel Hood,53,Mle,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [22]:
#15.	Remove rows where Feedback_Score is less than 1 or greater than 5
df = df[(df['Feedback_Score'] >= 1) & (df['Feedback_Score'] <= 5)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
2,6574,Daniel Cortez,105,Mle,Tajikistan,Montana,West Jennifermouth,hoffmancole@yahoo.com,2025-05-19,Active,...,0,2025-08-08,2025-01-30,UPI,3.7,That resource sound.,Returning,2025-04-24,web,0.00
3,3377,Cindy Barber,100,Female,Chile,Ohio,Staceyberg,carpenterlinda@yahoo.com,2024-08-19,Active,...,9,2025-03-25,2025-01-24,Debit,4.4,Customer international base media.,New,2025-07-28,App,7361.37
4,5107,William Patel,110,Mle,Timor-Leste,Hawaii,South Hollyfort,blairivan@lyons-christensen.org,2020-05-04,NaN,...,7,2025-05-04,2025-04-26,up,2.5,Sport concern entire.,New,NaN,App,6561.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2657,1802,Brian Simon,114,Mle,Latvia,Tennessee,New Cynthia,uwalker@graham.org,2021-04-27,Banned,...,7,2025-09-24,2025-06-28,Crdit,1.0,Computer card Republican friend score short.,Returning,2025-08-22,Phone,2144.66
2710,1332,Courtney Jenkins,99,f,Mauritania,Alabama,Gonzalezton,jenniferreid@hotmail.com,2025-10-13,Active,...,2,2025-08-14,2025-04-01,Crdit,3.8,Tree to its no.,New,2025-04-29,Phone,332.48
2955,675,NaN,74,Male,Netherlands Antilles,Tennessee,Lake Beverly,nicholas42@yahoo.com,2025-09-17,Active,...,3,2025-10-07,2025-01-31,up,2.7,Last building agent project view fly brother.,NaN,2025-05-02,App,2915.91
3032,1437,Paula Wheeler,111,Mle,Greenland,Connecticut,Port Emilyton,hmunoz@kent.com,2024-09-14,NaN,...,15,2025-08-09,2025-01-02,up,2.1,Almost director simple economic turn.,Returning,2025-06-01,web,8497.50
3039,201,Kirk Clayton PhD,80,f,Russian Federation,South Carolina,Andrewton,cbennett@wright.com,2022-01-24,NaN,...,5,2025-10-08,2025-08-06,Crdit,1.8,Order city officer include bag.,New,2025-01-30,Web,4788.95

In [23]:
#16.	Remove rows where Delivery_Date is before Purchase_Date
df = df[pd.to_datetime(df['Delivery_Date']) >= pd.to_datetime(df['Purchase_Date'])]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Mle,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Mle,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Mle,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [24]:
#17.	Fix typos in Gender column (e.g., "Mle" → "Male", "f" → "Female").
df['Gender'] = df['Gender'].replace({'Mle': 'Male', 'mle': 'Male', 'f': 'Female', 'F': 'Female', 'Othr': 'Other'})
df

/tmp/ipython-input-3777998066.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({'Mle': 'Male', 'mle': 'Male', 'f': 'Female', 'F': 'Female', 'Othr': 'Other'})

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [25]:
#18.	Fix typos in Payment_Type column
df['Payment_Type'] = df['Payment_Type'].replace({'Cahs': 'Cash', 'CASH': 'Cash','up':'UPI','Crdit':'Credit','credit cart': 'Credit Card','debit': 'Debit Card', 'online pay': 'Online Payment'})
df

/tmp/ipython-input-1868257649.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment_Type'] = df['Payment_Type'].replace({'Cahs': 'Cash', 'CASH': 'Cash','up':'UPI','Crdit':'Credit','credit cart': 'Credit Card','debit': 'Debit Card', 'online pay': 'Online Payment'})

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [26]:
#19.	Standardize Account_Status column (Active/Inactive/Banned)
df['Account_Status'] = df['Account_Status'].str.title()
df['Account_Status'] = df['Account_Status'].replace({'Actv': 'Active', 'Inactiv': 'Inactive', 'Banned_User': 'Banned'})
df

/tmp/ipython-input-1313897513.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Account_Status'] = df['Account_Status'].str.title()
/tmp/ipython-input-1313897513.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Account_Status'] = df['Account_Status'].replace({'Actv': 'Active', 'Inactiv': 'Inactive', 'Banned_User': 'Banned'})

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [27]:
#20.	Remove invalid email addresses.
df = df[df['Email'].str.contains(r'^[\w\.-]+@[\w\.-]+\.\w+$', na=False)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [28]:
#21.	Fetch all orders where Price > 500
orders_price_gt_500 = df[df['Price'] > 500]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [29]:
#22.	Fetch all orders where Feedback_Score < 3.
orders_feedback_lt_3 = df[df['Feedback_Score'] < 3]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [30]:
#23.	Fetch all VIP customers (Customer_Loyalty = "VIP") with Total_Purchase > 1000
vip_customers = df[(df['Customer_Loyalty'] == 'VIP') & (df['Total_Purchase'] > 1000)]
df

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,UPI,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Credit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaN,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Credit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,UPI,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [31]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'Country', 'State', 'City',
       'Email', 'Signup_Date', 'Account_Status', 'Product_ID', 'Product_Name',
       'Category', 'Price', 'Discount', 'Quantity', 'Purchase_Date',
       'Delivery_Date', 'Payment_Type', 'Feedback_Score', 'Comments',
       'Customer_Loyalty', 'Last_Login', 'Signup_Channel', 'Total_Purchase'],
      dtype='object')

In [32]:
#24.	Fetch all orders where Account_Status = "Banned".
df=df[df['Account_Status']=='Banned']

In [33]:
#25.	Fetch all orders delivered late (Delivery_Date - Purchase_Date > 7 days).
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])
late_orders = df[(df['Delivery_Date'] - df['Purchase_Date']).dt.days > 7]
df

/tmp/ipython-input-2711530274.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
/tmp/ipython-input-2711530274.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
23,7144,Edgar Hughes,10,Male,Japan,Maryland,Michelleberg,nbrooks@yahoo.com,2023-07-16,Banned,...,11,2025-05-24,2025-09-25,Debit,3.0,Machine memory girl short budget.,NaN,2025-05-04,web,1978.13
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
31,116,Kathy Hernandez,103,Female,Lebanon,North Dakota,Barreramouth,jmoon@fitzpatrick.com,2021-02-23,Banned,...,5,2025-08-07,2025-09-23,UPI,3.8,Store base opportunity yeah activity.,New,2025-05-23,Web,3578.55
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
52,1962,NaN,66,Other,Cape Verde,NaN,Joneshaven,pmorales@mclean-palmer.org,2022-02-12,Banned,...,20,2025-06-15,2025-06-15,Cash,4.8,Second girl write hope.,Returning,NaN,App,1659.00
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
98,7079,Katie Chavez,17,Female,Serbia,Arizona,Codybury,csmith@yahoo.com,2020-05-24,Banned,...,1,2025-02-20,2025-03-11,Cash,3.2,Walk the police remember physical at education.,VIP,2025-03-25,Phone,335.75
103,1139,Danielle Perez,88,Female,Venezuela,Colorado,Kellyshire,watkinsbenjamin@hotmail.com,2023-09-04,Banned,...,16,2025-01-13,2025-09-25,Cash,2.9,Beat everybody future member father free yet.,NaN,NaN,web,6683.20
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
116,5166,NaN,18,Male,Burkina Faso,Tennessee,South Logan,tannermichelle@hotmail.com,2025-06-09,Banned,...,1,2025-06-06,2025-08-26,Credit,1.6,Kitchen method five so minute method me.,Returning,2025-01-31,Phone,402.98
128,3471,Frederick Pierce,108,Female,Australia,Pennsylvania,Denisefurt,ocooke@yahoo.com,2024-03-25,Banned,...,8,2025-03-13,2025-03-27,UPI,4.7,Sort draw hot threat such Republican society o...,NaN,2025-07-22,app,2557.20
153,454,Meghan Bowen,44,Female,Norfolk Island,California,Yolandabury,dgaines@gmail.com,2023-02-05,Banned,...,15,2025-01-01,2025-08-17,UPI,3.7,NaN,NaN,2025-08-20,App,7222.65
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,UPI,4.6,NaN,VIP,NaN,App,1775.10
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Credit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
274,7892,NaN,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaN,app,6144.80
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
444,7806,Ernest Kirby,71,Other,Hong Kong,South Dakota,West Janetburgh,lcosta@yahoo.com,2020-07-23,Banned,...,18,2025-04-08,2025-06-22,Credit,4.7,NaN,New,2025-06-03,Web,9969.66
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Credit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
611,3143,Kathleen Gibbs,7,Other,Somalia,Rhode Island,Matthewton,smithsonya@mann-lee.net,2023-10-12,Banned,...,10,2025-01-27,2025-09-30,Debit,2.6,Stop item them industry report.,Returning,2025-03-28,web,7154.30
663,5344,Carolyn Clayton,103,Male,Andorra,Texas,Allisonhaven,barry51@russell-jones.net,2020-06-10,Banned,...,9,2025-06-22,2025-09-27,Credit,3.9,This kitchen receive community.,Returning,2025-09-17,app,5535.36
812,2120,Joseph Benjamin,54,Male,Algeria,Colorado,Arnoldview,howetanner@gmail.com,2020-02-19,Banned,...,15,2025-07-17,2025-10-12,Debit,2.9,Than either itself give still.,NaN,2025-04-02,Phone,6113.85
985,989,Kevin Wood,114,Other,Congo,Oregon,Randolphside,rday@yahoo.com,2022-06-27,Banned,...,6,2025-04-05,2025-05-20,Credit,4.0,Allow majority increase.,New,2025-06-25,Phone,487.20
1214,4168,Alison Kelly,20,Female,Palestinian Territory,Colorado,Brownfurt,erictaylor@gmail.com,2023-04-11,Banned,...,10,2025-08-30,2025-09-23,UPI,2.1,Religious write health city color.,New,2025-09-06,App,5307.30
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Credit,3.6,Clearly business hair pretty.,Returning,NaN,app,8200.08
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaN,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Credit,4.9,NaN,VIP,2025-01-22,app,12697.58
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [34]:
#26.	Fetch all products in the "Electronics" category.
df_electronics = df[df['Category']== "Electronics"]

In [35]:
#27.	Fetch all customers from "India".
df=df[df['Country']=='India']

In [36]:
#28.	Fetch all orders where Quantity > 10
df=df[df['Quantity'] > 10]

In [37]:
#29.	Fetch all orders where Discount > 50
df=df[df['Discount'] > 50]
df

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [38]:
#30.	Fetch all orders where Price * Quantity > 1000.
df=df[df['Price']*df['Quantity']>1000]
df

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [39]:
#31.	Using Customer_ID, fetch all orders with the customer details
customer_df = df[['Customer_ID', 'Name', 'Email', 'Country', 'Account_Status']].drop_duplicates()

In [40]:
#32.	Using Product_ID, fetch all orders with product details.
product_df = df[['Product_ID', 'Product_Name', 'Category', 'Price']].drop_duplicates()

In [41]:
#33.	Combine customer and product info into the orders table.
merged_df = df.merge(customer_df, on='Customer_ID', how='left')
merged_df = merged_df.merge(product_df, on='Product_ID', how='left')
df

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [42]:
#34.	Calculate total purchase per customer (sum(Price * Quantity)).
df['Total_Purchase'] = df['Price'] * df['Quantity']
total_purchase = df.groupby('Customer_ID')['Total_Purchase'].sum()
df

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [43]:
#35.	Calculate average feedback per product
avg_feedback = df.groupby('Product_ID')['Feedback_Score'].mean().reset_index
df

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [44]:
#36.	Identify customers who only ordered "Electronics
top_vip = df[df[df['Customer_Loyalty'] == 'VIP'].groupby('Customer_ID')['Total_Purchase']]

In [45]:
#37.Identify top 10 VIP customers by total purchase amount.
vip = total_purchase.sort_values(ascending=False).head(10)
vip

Series([], Name: Total_Purchase, dtype: float64)

In [46]:
#38.Identify products that were never ordered.
orderproduct=df['Product_ID'].unique()
allproduct=df[~df['Product_ID'].isin(orderproduct)]

In [47]:
#39.Identify orders with missing customer info
missing_customer = df[df['Customer_ID'].isna()]

In [48]:
#40.Identify orders with missing product info.
missing_product = df[df['Product_ID'].isna()]
orders_missing_product = df[df['Product_Name'].isna() | df['Category'].isna()]

In [49]:
#41.Add a column Total_Purchase = Price * Quantity.
df['Total_Purchase'] = df['Price'] * df['Quantity']

In [50]:
#42.Add a column Discounted_Price = Price - Discount.
df['Discounted_Price'] = df['Price'] - df['Discount']

In [51]:
#43.Add a column Delivery_Duration = Delivery_Date - Purchase_Date.
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
df['Delivery_Duration'] = (df['Delivery_Date'] - df['Purchase_Date']).dt.days

In [52]:
#44.Create Age_Group for customers (Child/Teen/Adult/Senior).
def age_group(age):
    if age < 13:
        return 'Child'
    elif age < 20:
        return 'Teen'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['Age'].apply(age_group)

In [53]:
#45.Create Loyalty_Level based on total purchase.
def loyalty_level(total):
    if total < 1000:
        return 'Bronze'
    elif total < 5000:
        return 'Silver'
    elif total < 10000:
        return 'Gold'
    else:
        return 'Platinum'

df['Loyalty_Level'] = df['Total_Purchase'].apply(loyalty_level)

In [54]:
#46.Encode Gender numerically (Male=1, Female=2, Other=3).
df['Gender_Code'] = df['Gender'].map({'Male': 1, 'Female': 2, 'Other': 3})

In [55]:
#47.Encode Account_Status numerically.
df['Account_Status_Code'] = df['Account_Status'].map({'Active': 1, 'Inactive': 0})

In [56]:
#48.Standardize Country names (capitalize first letters).
df['Country'] = df['Country'].str.title()

In [57]:

#49.Standardize Payment_Type strings.
df['Payment_Type'] = df['Payment_Type'].str.strip().str.title()

In [58]:
#50.Remove leading/trailing spaces and lowercase all string columns.
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [59]:

#51.Find top 5 products by total revenue (Price * Quantity).
top_products = df.groupby('Product_ID')['Total_Purchase'].sum().nlargest(5)

In [60]:
#52.Find top 5 customers by total purchase.
top_5_customers=(df.groupby(['Customer_ID'])['Total_Purchase'].sum().reset_index().sort_values(by='Total_Purchase', ascending=False).head(5))

In [61]:
#53.Calculate average discount per category.
avg_dis=(df.groupby('Category')['Discount'].mean().reset_index().sort_values(by='Discount', ascending=False))

In [62]:
#54.Calculate average feedback per product category.
avg_feedback=(df.groupby('Category')['Feedback_Score'].mean().reset_index().sort_values(by='Feedback_Score', ascending=False))

In [63]:
#55.Identify the most popular payment type.
popular_payment=(df['Payment_Type'].value_counts().reset_index().rename(columns={'index':'Payment_Type','Payment_Type':'Count'}).head(1))

In [64]:
#56.Find the customer with the highest single order value.
df['Order_Value'] = df['Price'] * df['Quantity']
highest_order = df.sort_values(by='Order_Value', ascending=False).head(1)

In [65]:
#57.Identify customers who placed more than 5 orders.
customer_orders=df.groupby('Customer_ID').size()
frequent_customers=customer_orders[customer_orders > 5]

In [66]:
#58.Sort orders by Delivery_Duration descending.
df=df.sort_values(by='Delivery_Duration',ascending=False)

In [67]:
#59.Find products with maximum and minimum feedback.
mafp=df.sort_values(by='Feedback_Score', ascending=False).head(1)[['Product_ID', 'Product_Name', 'Feedback_Score']]
mifp=df.sort_values(by='Feedback_Score', ascending=True).head(1)[['Product_ID', 'Product_Name', 'Feedback_Score']]

In [68]:
#60.Group orders by Country and Category, and calculate total Total_Purchase.
TP= (df.groupby(['Country', 'Category'])['Total_Purchase'].sum().reset_index().sort_values(by='Total_Purchase',ascending=False))